### ISSUE TITLE
NullPointerException in "canRead()" if delegate was removed

### ISSUE THREAD

**Issue by wglanzer** [aditosoftware/propertly#1]
java.lang.NullPointerException
 	at de.adito.propertly.core.api.DelegatingNode.canRead(DelegatingNode.java:108)
 	at de.adito.propertly.core.api.HierarchyProperty.canRead(HierarchyProperty.java:73)
 	at de.adito.propertly.core.api.HierarchyProperty.getValue(HierarchyProperty.java:57)
 	at de.adito.propertly.core.api.HierarchyProperty.getHierarchy(HierarchyProperty.java:47)

**Comment by jboesl** [comment]
I think 'canRead()' should return 'false' for a null delegate.
